### ISSUE TITLE
Siri doesn’t respond correctly to shutdown

### ISSUE THREAD

**Issue by redeemer666** [alisdairjsmyth/homebridge-ambiclimate-thermostat#3]
When you tell Siri to shut down the AmbiClimate, it switch off and immediately on again, even if in home app tells is not active. The only way to fully shut down it is to do the action via the ambiclimate app

**Comment by alisdairjsmyth** [comment]
What is the Siri command you are using?

**Comment by redeemer666** [comment]
Turn off “name of ambiclimate thermostat in home” that differs from the fan device

**Comment by redeemer666** [comment]
BTW I only have the thermostat plugin installed, not both. It can be that the cause of this issue?
